# Dependencies
markdown:         redcarpet
redcarpet:
    extensions: ['smart', 'no_intra_emphasis', 'tables', 'strikethrough', 'superscript']


highlighter:      pygments

# Sass options
sass:
  style: compressed

# Permalinks
permalink:        pretty

# Setup
title:            "Joseph Cooper"
description:      "Personal website and blog"
tagline:          "Android, Haskell, Raspberry Pi and whatever else"

author:
  name:           'Joseph Cooper'
url:              "https://grodin.github.io"
baseurl:          "/"
paginate:         4
paginate_path:    "blog/page:num"
baseurl: '/'

# Custom vars
version:          1.2.1

# Defaults
defaults:
  -
    scope:
      path: "" # applies only to files with blog in their path
      type: "drafts" # applies only to draft posts
    values:
      isdraft: true

# This is the list of pages to incldue in the header of the website.
pages_list:
  Archive: '/archive/'
  Feed: '/atom.xml'

# Allow URL Redirects:
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# list of files to exclude from site generation
exclude: [README.*, LICENSE.*, blog.github.sublime*, Rakefile*, Gemfile*]
