# Dependencies
markdown:         kramdown

highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Joseph Cooper's devblog
tagline:          'Android, Haskell, Raspberry Pi and whatever else'

author:
  name:           'Joseph Cooper'
  #url:            https://

paginate:         4

# Custom vars
version:          1.0.0


# This is the list of pages to incldue in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
