# Dependencies
markdown:         kramdown
# ~ redcarpet:
  # ~ extensions: ["tables"]

pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Joseph Cooper's devblog
tagline:          'Android, Haskell, Raspberry Pi and whatever else'
#url:              http://www.joshualande.com
#shorturl:         joshualande.com

author:
  name:           'Joseph Cooper'
  #url:            https://

paginate:         4

# Custom vars
version:          1.0.0

#github:
#  repo:           github.com/joshualande/joshualande.github.io

# This is the list of pages to incldue in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
