name: Build with Zola

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.18

      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: build with Zola
        run: zola build

      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

